[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dev-utilities"
dynamic = ["version"]
description = ''
readme = "README.txt"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = [
    { name = "José Albert Cruz Almaguer", email = "jalbertcruz@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "cattrs~=24.1.2",
    "python-decouple~=3.8",
    "typer~=0.15.1",
    "rich~=13.9.4",
    "more-itertools~=10.5.0",
    "GitPython~=3.1.44",
    "jinja2~=3.1.6",
    "python-slugify~=8.0.4",
    "requests~=2.32.3",
    "pydot~=3.0.3",
    "more-itertools>=10.5.0",
    "pynvim>=0.5.2",
    "docker~=7.1.0",
    "PyYAML~=6.0.2",
    "tomlkit~=0.13.3",
]

[dependency-groups]
dev = [
    "coverage[toml]>=7.6.10",
    "pytest>=8.3.4",
]

[project.urls]
source = "https://github.com/jdev-ops/dev-utilities"

[project.scripts]
# pre-commit
check-branch-name = "dev_utilities.git_policy_jira.check_branch_name:main"
# pre-push
check-commits-are-signed = "dev_utilities.git_policy_jira.check_commits_are_signed:main"
# prepare-commit-msg
prepare-commit-msg-from-jira-issue = "dev_utilities.git_policy_jira.prepare_commit_msg_from_jira_issue:main"
dot2d2 = "dev_utilities.dev_conversors.main:dot_to_d2"
non-jira-branch = "dev_utilities.git_policy_jira.create_non_jira_branch:main"
_to-package-elf-deps = "dev_utilities.reverse_engineering.elf_dependency_finder:run"
_update-lazyvim-json = "dev_utilities.nvim.update_lazyvim_json:run"
_nvim-scala-compile-quickfix-loader = "dev_utilities.nvim.scala_compile_quickfix_loader:run"
_boxes-names = "dev_utilities.containers.pdi.docker_setup:boxes_names"

[tool.hatch.version]
path = "src/dev_utilities/__about__.py"

[tool.hatch.envs.default]
dependencies = [
    "coverage[toml]",
    "pytest",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.13"]

[tool.hatch.envs.types]
dependencies = [
    "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/dev_utilities tests}"

[tool.hatch.build.targets.sdist]
exclude = [
    "bin/*",
    "devpi/*",
]
include = [
    "src/",
]
#core-metadata-version = "2.2"

[tool.hatch.build.targets.wheel]
packages = [
    "src/dev_utilities",
]
